<?php

namespace RecrutementTest\RecrutementTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * candidatTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class candidatTestRepository extends EntityRepository
{
}
