<?php

namespace RecrutementTest\RecrutementTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends EntityRepository
{
    
    public function convertFromArrayToReponsesCollection($aQuestions) {
        
        $aReponses = null;
        
        foreach ($aQuestions as $key => $aQuestion) {

            if ("reponse_a" == $key || "reponse_b" == $key || "reponse_c" == $key || "reponse_d" == $key) {
                
                $oReponse = new Reponse();
                $oReponse->setIntitule($aQuestion[$key]);
                
                if ($key == $aQuestion['bonne_reponse']) {
                    $oReponse->setIsTrue(true);
                }
                else {
                    $oReponse->setIsTrue(false);
                }
                
                $aReponses[] = $oReponse;
            }
        }
        
        return $aReponses;
    }
    
    
    public function truncateQuestion($oQuestion) {
        
        $oEm = $this->getEntityManager();
        $aReponses = $this->findByQuestion($oQuestion);
        
        if (null != $aReponses) {
            foreach ($aReponses as $oReponse) {
                
                $oEm->remove($oReponse);
                $oEm->flush();
            }
            $bReturn = true;
        }
        else {
            $bReturn = false;
        }
        
        return $bReturn;
    }
}
