<?php

namespace RecrutementTest\RecrutementTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{
    
    public function DeleteTestInCascade($oTest) {
        
        $oEm = $this->getEntityManager();
        $oQuestionRepository = $oEm->getRepository("RecrutementTestBundle:Question");
        $bResult = $oQuestionRepository->truncateTest($oTest);
        
        return $bResult;
    }
    
    
}
